name: GitHub Pages
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build HTML
        uses: ammaraskar/sphinx-action@0.4
        with:
          pre-build-command: "sphinx-apidoc -f -e -o source doc_test/"
          docs-folder: "docs/"
          build-command: "make html"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: html-docs
          path: build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' # Set a branch name to trigger deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html

